title: LateNiteRxse
email: sonicthehamilton.ar@gmail.com
description: > 
  The band of renegades release their 1st EP premiering new singles every Tuesday & Friday til March 2017.
baseurl: "" 
url: "https://lateniterxse.com" 
twitter_username: blyrsxe
github_username: bldy-rxse

tracking:
  google_analytics_id: 'UA-90595388-1'

facebook:
  app_id: 1350569341674398

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json

