title: LateNiteRxse
email: bldyrosestudios@gmail.com
description: > 
  Catch BLDY RXSE's premiere music flick: Hanz - Thrill, a #LateNiteRxse special. Only on lateniterxse.com
baseurl: "" 
url: "http://lateniterxse.com" 
twitter_username: bldyrsxe
github_username: bldy-rxse

tracking:
  google_analytics_id: 'UA-90595388-1'

facebook:
  app_id: 1350569341674398

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json

